packages:
  - ./
  - example

overrides:
  "@antfu/eslint-config>@eslint/markdown": "-"
  "@antfu/eslint-config>@stylistic/eslint-plugin": "-"
  "@antfu/eslint-config>eslint-plugin-jsonc": "-"
  "@antfu/eslint-config>eslint-plugin-toml": "-"
  "@antfu/eslint-config>eslint-plugin-vue": "-"
  "@antfu/eslint-config>eslint-processor-vue-blocks": "-"
  "@antfu/eslint-config>jsonc-eslint-parser": "-"
  "@antfu/eslint-config>toml-eslint-parser": "-"
  "@antfu/eslint-config>vitest": "-"
  eslint-plugin-pnpm>jsonc-eslint-parser: "-"

allowBuilds:
  esbuild: true
  simple-git-hooks: false
