name: tflint

on:
  push:
    branches:
      - main
    paths:
      - example/infra/**
      - .github/workflows/tflint.yml
  pull_request:
    paths:
      - example/infra/**
      - .github/workflows/tflint.yml

jobs:
  lints:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: ~/.tflint.d/plugins
          key: tflint-v2-${{ hashFiles('.tflint.hcl') }}
          restore-keys: |
            tflint-v2-

      - uses: terraform-linters/setup-tflint@v3

      - run: tflint --init
        working-directory: example/infra

      - run: tflint -f compact
        working-directory: example/infra
